#!/usr/bin/env bash
# 00_detect_env.sh — AUTO-DETECT the production environment on the VPS and bake it in.
# Writes deploy.env (+ compose/.env + backend/.env from the live container).
# Non-destructive. Stops if detection is ambiguous (never guesses silently).
source "$(dirname "${BASH_SOURCE[0]}")/../lib/common.sh"
need_cmd docker

log "Detecting production backend container..."
BACKEND_CANDIDATES="$(detect_one 'arbicore.*back|:8001->|:8001/')"
BACKEND_COUNT="$(printf '%s\n' "$BACKEND_CANDIDATES" | grep -c . || true)"
[ "$BACKEND_COUNT" = "1" ] || die "expected exactly 1 backend container, found [$BACKEND_COUNT]: $BACKEND_CANDIDATES
  -> set BACKEND_OLD=<name> in deploy.env manually and re-run preflight."
BACKEND_OLD="$(printf '%s' "$BACKEND_CANDIDATES" | tr -d '[:space:]')"
ok "backend container: $BACKEND_OLD"

log "Detecting production Mongo container..."
MONGO_CANDIDATES="$(detect_one 'mongo')"
MONGO_COUNT="$(printf '%s\n' "$MONGO_CANDIDATES" | grep -c . || true)"
[ "$MONGO_COUNT" = "1" ] || die "expected exactly 1 mongo container, found [$MONGO_COUNT]: $MONGO_CANDIDATES
  -> set MONGO_CONTAINER=<name> in deploy.env manually and re-run preflight."
MONGO_CONTAINER="$(printf '%s' "$MONGO_CANDIDATES" | tr -d '[:space:]')"
ok "mongo container: $MONGO_CONTAINER"

log "Detecting Docker network (shared with Mongo)..."
NETWORK_NAME="$(docker inspect -f '{{range $k,$v := .NetworkSettings.Networks}}{{$k}}{{"\n"}}{{end}}' "$MONGO_CONTAINER" | grep -v '^$' | head -n1)"
[ -n "$NETWORK_NAME" ] || die "could not determine Mongo network"
ok "network: $NETWORK_NAME"

log "Recording Mongo volume / bind-mount (for preservation confirmation)..."
MONGO_MOUNTS="$(docker inspect -f '{{range .Mounts}}{{.Type}}:{{.Source}}->{{.Destination}}; {{end}}' "$MONGO_CONTAINER")"
ok "mongo mounts: ${MONGO_MOUNTS:-<none/anonymous>}"

log "Resolving Mongo hostname on the network (for new backend MONGO_URL)..."
# Prefer the existing backend's MONGO_URL; fall back to the mongo container name.
OLD_ENV="$(docker inspect -f '{{range .Config.Env}}{{println .}}{{end}}' "$BACKEND_OLD" 2>/dev/null || true)"
get_old(){ printf '%s\n' "$OLD_ENV" | grep -E "^$1=" | head -n1 | cut -d= -f2-; }

MONGO_URL="$(get_old MONGO_URL)"; [ -n "$MONGO_URL" ] || MONGO_URL="mongodb://${MONGO_CONTAINER}:27017"
DB_NAME="$(get_old DB_NAME)";     [ -n "$DB_NAME" ] || DB_NAME="arbicore_x_prod"
ok "MONGO_URL: $(printf '%s' "$MONGO_URL" | sed -E 's#//[^@]*@#//***@#')   DB_NAME: $DB_NAME"

# Provenance / image tag
GITSHA="$(git -C "$ROOT_DIR" rev-parse --short HEAD 2>/dev/null || echo "$(date +%Y%m%d)")"
GITTAG="$(git -C "$ROOT_DIR" describe --tags --always --dirty 2>/dev/null || echo "$GITSHA")"
BUILD_TIME="$(date -u +%FT%TZ)"
APP_VERSION="$GITTAG"
IMAGE_TAG="arbicore-x-backend:0.1.0-realign-${GITSHA}"
BACKEND_NEW="arbicore-x-backend"
[ "$BACKEND_NEW" = "$BACKEND_OLD" ] && BACKEND_NEW="arbicore-x-backend-new"  # avoid name collision

log "Writing deploy.env ..."
cat > "$DEPLOY_ENV" <<EOF
# AUTO-GENERATED by 00_detect_env.sh on $(date -u +%FT%TZ). Do not commit secrets.
BACKEND_OLD=${BACKEND_OLD}
BACKEND_NEW=${BACKEND_NEW}
MONGO_CONTAINER=${MONGO_CONTAINER}
NETWORK_NAME=${NETWORK_NAME}
IMAGE_TAG=${IMAGE_TAG}
GITSHA=${GITSHA}
DB_NAME=${DB_NAME}
MONGO_MOUNTS=${MONGO_MOUNTS}
EOF
ok "deploy.env written"

log "Writing compose/.env (for compose interpolation) ..."
cat > "$COMPOSE_ENV" <<EOF
NETWORK_NAME=${NETWORK_NAME}
IMAGE_TAG=${IMAGE_TAG}
BACKEND_NEW=${BACKEND_NEW}
GITSHA=${GITSHA}
GITTAG=${GITTAG}
BUILD_TIME=${BUILD_TIME}
APP_VERSION=${APP_VERSION}
EOF
ok "compose/.env written"

log "Baking backend/.env from the LIVE production container (preserve exact config) ..."
mkdir -p "$(dirname "$BACKEND_ENV")" "$LOG_DIR"
: > "$BACKEND_ENV"; chmod 600 "$BACKEND_ENV"

# W2: refuse to write a near-empty .env if docker inspect produced nothing useful.
# The OLD container always has at least PATH/HOSTNAME plus a handful of app vars,
# so a capture under 5 lines is a strong indicator of an inspect failure.
OLD_ENV_LINES="$(printf '%s\n' "$OLD_ENV" | grep -c '=' || true)"
[ "$OLD_ENV_LINES" -ge 5 ] || die "OLD container env capture suspiciously empty ($OLD_ENV_LINES lines) — refusing to bake .env"

# B2 (hybrid application-variable copy):
# Inherit ONLY application-specific env vars from OLD; never inherit Docker/runtime/system
# vars (PATH, HOSTNAME, PYTHON_*, LANG, ...). An OLD variable is APPLICATION-LEVEL iff its
# name matches one of:
#   - a prefix in APP_PREFIX_RE      (ARBICORE_, MONGO_, DB_, JWT_, VAULT_, FEATURE_)
#   - a suffix in APP_SUFFIX_RE      (_API_KEY, _SECRET, _RPC_URL, _TOKEN, _WEBHOOK, _WEBHOOK_URL, _DSN)
#   - an explicit name in APP_EXPLICIT_RE (CORS_ORIGINS, LOG_LEVEL, SENTRY_DSN)
APP_PREFIX_RE='^(ARBICORE|MONGO|DB|JWT|VAULT|FEATURE)_'
APP_SUFFIX_RE='_(API_KEY|SECRET|RPC_URL|TOKEN|WEBHOOK|WEBHOOK_URL|DSN)$'
APP_EXPLICIT_RE='^(CORS_ORIGINS|LOG_LEVEL|SENTRY_DSN)$'

PARITY_TS="$(date -u +%Y%m%dT%H%M%SZ)"
PARITY_REPORT="${LOG_DIR}/env_parity_${PARITY_TS}.txt"
OLD_APP_KEYS="${LOG_DIR}/.env_old_app_keys_${PARITY_TS}"
NEW_APP_KEYS="${LOG_DIR}/.env_new_app_keys_${PARITY_TS}"
SKIPPED_LIST="${LOG_DIR}/.env_skipped_${PARITY_TS}"
: > "$OLD_APP_KEYS"; : > "$NEW_APP_KEYS"; : > "$SKIPPED_LIST"

COPIED=0
SKIPPED=0
while IFS= read -r line; do
  [ -z "$line" ] && continue
  case "$line" in *=*) : ;; *) continue ;; esac
  key="${line%%=*}"
  if echo "$key" | grep -Eq "$APP_PREFIX_RE" \
     || echo "$key" | grep -Eq "$APP_SUFFIX_RE" \
     || echo "$key" | grep -Eq "$APP_EXPLICIT_RE"; then
    echo "$line" >> "$BACKEND_ENV"
    echo "$key" >> "$OLD_APP_KEYS"
    COPIED=$((COPIED+1))
  else
    echo "$key" >> "$SKIPPED_LIST"
    SKIPPED=$((SKIPPED+1))
  fi
done <<< "$OLD_ENV"

# Guarantee the connection pivots are present (only added if OLD had nothing).
grep -q '^MONGO_URL=' "$BACKEND_ENV" || echo "MONGO_URL=${MONGO_URL}" >> "$BACKEND_ENV"
grep -q '^DB_NAME='   "$BACKEND_ENV" || echo "DB_NAME=${DB_NAME}"     >> "$BACKEND_ENV"
# Scanner-state preservation: only fall back if OLD set NEITHER flag explicitly.
# If OLD has ARBICORE_SCANNER_CEX_ARB=off, it was already copied above and is preserved.
grep -q '^ARBICORE_SCANNER_CEX_ARB='     "$BACKEND_ENV" || echo "ARBICORE_SCANNER_CEX_ARB=on"     >> "$BACKEND_ENV"
grep -q '^ARBICORE_SCANNER_FUNDING_ARB=' "$BACKEND_ENV" || echo "ARBICORE_SCANNER_FUNDING_ARB=on" >> "$BACKEND_ENV"

# Build NEW key set from the file we just wrote and emit the parity report.
grep -E '^[A-Za-z_][A-Za-z0-9_]*=' "$BACKEND_ENV" | cut -d= -f1 | sort -u > "$NEW_APP_KEYS"
sort -u -o "$OLD_APP_KEYS" "$OLD_APP_KEYS"

OLD_APP_COUNT="$(wc -l < "$OLD_APP_KEYS" | tr -d ' ')"
NEW_APP_COUNT="$(wc -l < "$NEW_APP_KEYS" | tr -d ' ')"
MISSING="$(comm -23 "$OLD_APP_KEYS" "$NEW_APP_KEYS" | tr '\n' ' ')"
ADDED="$(comm -13 "$OLD_APP_KEYS" "$NEW_APP_KEYS"  | tr '\n' ' ')"
SKIPPED_KEYS="$(tr '\n' ' ' < "$SKIPPED_LIST")"

{
  echo "=== ENV PARITY REPORT @ ${PARITY_TS} ==="
  echo "  OLD application var count   : $OLD_APP_COUNT"
  echo "  NEW application var count   : $NEW_APP_COUNT"
  echo "  OLD-only vars (MISSING)     : ${MISSING:-<none>}"
  echo "  NEW-only vars (ADDED)       : ${ADDED:-<none>}"
  echo "  Non-app OLD vars skipped    : $SKIPPED  (system/runtime housekeeping)"
  echo "  Skipped key names           : ${SKIPPED_KEYS:-<none>}"
} | tee "$PARITY_REPORT"

# Defensive invariant: every OLD application var MUST be present in NEW.
if [ -n "$MISSING" ]; then
  die "ENV PARITY FAIL — OLD application vars not copied: $MISSING"
fi

rm -f "$OLD_APP_KEYS" "$NEW_APP_KEYS" "$SKIPPED_LIST"

c_green "ENV PARITY PASS (all $OLD_APP_COUNT OLD application vars preserved)"
ok "backend/.env baked ($NEW_APP_COUNT vars total; $COPIED inherited from OLD; report: $PARITY_REPORT; secrets not printed)"

c_green "DETECTION COMPLETE — no placeholders remain. Review deploy.env, then run steps/01_preflight.sh"
