[profile.default]
src = "contracts"
test = "contracts/tests"
script = "script"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
solc_version = "0.8.24"
evm_version = "paris"
via_ir = true
bytecode_hash = "none"
cbor_metadata = false
gas_reports = ["FlashLoanReceiver"]
ffi = false

# Coverage / verbosity defaults
verbosity = 2

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = false
int_types = "long"
quote_style = "double"

[rpc_endpoints]
base            = "${BASE_RPC_URL}"
base_sepolia    = "${BASE_SEPOLIA_RPC_URL}"

[etherscan]
base            = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api", chain = 8453 }
base_sepolia    = { key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api", chain = 84532 }
