#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# ArbiCore X — flash-loan limited-live readiness audit runner (repo tooling).
#
# READ-ONLY / SAFE: this runner ONLY executes the deterministic, offline
# regression suite that guards the flash-loan verification pipeline. It NEVER
# signs, NEVER broadcasts, NEVER enables Live/Limited-Live, and NEVER mutates
# any deployment. It emits an audit_run_id so a run can be correlated with the
# diagnostic provenance stamped onto persisted evidence bundles.
#
# Usage:
#   scripts/run_vps_validator_audit.sh
#
# On the VPS, Codex may additionally run the live validators
# (python -m scripts.m3_0_vps_validate) which require real Base RPC / Mongo;
# those are intentionally NOT invoked here to keep this runner hermetic.
# ---------------------------------------------------------------------------
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BACKEND_DIR="${REPO_ROOT}/app/backend"
# Wrapper-level correlation label ONLY. Deliberately NOT named ARBICORE_AUDIT_RUN_ID
# so it can never shadow the M3 evidence-isolation selector — the REAL audit_run_id
# is generated by the canonical scanner and reported by the live phase below.
AUDIT_WRAPPER_ID="flarb_audit_wrapper:$(date -u +%Y%m%dT%H%M%SZ):$(head -c4 /dev/urandom | od -An -tx1 | tr -d ' \n')"

echo "=============================================================="
echo "ArbiCore X flash-loan readiness audit"
echo "wrapper_id   : ${AUDIT_WRAPPER_ID}"
echo "repo_root    : ${REPO_ROOT}"
echo "git_sha      : $(git -C "${REPO_ROOT}" rev-parse HEAD 2>/dev/null || echo unknown)"
echo "git_branch   : $(git -C "${REPO_ROOT}" rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)"
echo "=============================================================="

# Deterministic guards for the safety-critical flash-loan pipeline. These are
# the invariants that MUST hold before any VPS live validation is attempted.
TESTS=(
  "tests/test_flashloan_partial_quote_economics.py"
  "tests/test_flashloan_diagnostic_provenance.py"
  "tests/test_flashloan_audit_evidence_filter.py"
  "tests/test_flashloan_canonical_audit_runner.py"
  "tests/test_m2_1_live_quote_provider.py"
  "tests/test_m2_2_real_tvl_gate8.py"
  "tests/test_m2_3_evidence_bundle.py"
  "tests/test_d6_1_economics_and_gates.py"
  "tests/test_economics_swap_fee_double_count.py"
  "tests/test_m3_0_pre_broadcast.py"
  "tests/test_m3_0_diagnostic_ordering.py"
)

cd "${BACKEND_DIR}"
echo "Running ${#TESTS[@]} deterministic regression modules..."
python -m pytest "${TESTS[@]}" -q -p no:cacheprovider
STATUS=$?

# ---------------------------------------------------------------------------
# OPTIONAL LIVE PHASE (VPS only): run exactly ONE canonical scanner tick,
# capture the ACTUAL audit_run_id + scanner_tick_id, isolate that run's
# evidence, print the candidate ledger, and expose exact M3 selectors.
# Enabled only when MONGO_URL + DB_NAME are configured AND the operator opts in
# with ARBICORE_RUN_LIVE_AUDIT=1. READ-ONLY: never signs / broadcasts / prints
# secrets. Does not affect the pass/fail status of the deterministic guards.
# ---------------------------------------------------------------------------
if [ "${STATUS}" -eq 0 ] \
   && [ "${ARBICORE_RUN_LIVE_AUDIT:-0}" = "1" ] \
   && [ -n "${MONGO_URL:-}" ] && [ -n "${DB_NAME:-}" ]; then
  echo "--------------------------------------------------------------"
  echo "LIVE PHASE: single canonical audit tick (read-only)"
  # The Python runner emits ONLY ids/status/counts (no secrets).
  python -m scripts.vps_canonical_audit || echo "live audit phase reported an error (fail closed)"
  echo "--------------------------------------------------------------"
fi

echo "=============================================================="
if [ "${STATUS}" -eq 0 ]; then
  echo "AUDIT RESULT: PASS (code-level flash-loan guards green)"
  echo "NOTE: code-ready only. Real VPS live validation (RPC/Mongo) is separate."
else
  echo "AUDIT RESULT: FAIL (see failures above) — NOT ready for VPS validation"
fi
echo "wrapper_id   : ${AUDIT_WRAPPER_ID}"
echo "=============================================================="
exit "${STATUS}"
