#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# ArbiCore X — flash-loan limited-live readiness audit runner (repo tooling).
#
# READ-ONLY / SAFE: this runner ONLY executes the deterministic, offline
# regression suite that guards the flash-loan verification pipeline. It NEVER
# signs, NEVER broadcasts, NEVER enables Live/Limited-Live, and NEVER mutates
# any deployment. It emits an audit_run_id so a run can be correlated with the
# diagnostic provenance stamped onto persisted evidence bundles.
#
# Usage:
#   scripts/run_vps_validator_audit.sh
#
# On the VPS, Codex may additionally run the live validators
# (python3 -m scripts.m3_0_vps_validate) which require real Base RPC / Mongo;
# those are intentionally NOT invoked here to keep this runner hermetic.
# ---------------------------------------------------------------------------
set -euo pipefail

# ---------------------------------------------------------------------------
# Interpreter selection. The disposable validation image ships Python 3 as
# ``python3`` (Ubuntu provides no bare ``python`` alias). Prefer an explicit
# override, then ``python3``, then ``python`` — using whichever is actually
# present in THIS image, without creating a host-level symlink or installing
# anything. Fail closed with a clear message if none is available.
PY="${ARBICORE_PYTHON:-}"
if [ -n "${PY}" ]; then
  if ! command -v "${PY}" >/dev/null 2>&1; then
    echo "ERROR: ARBICORE_PYTHON='${PY}' is not an available interpreter." >&2
    exit 127
  fi
elif command -v python3 >/dev/null 2>&1; then
  PY="python3"
elif command -v python >/dev/null 2>&1; then
  PY="python"
else
  echo "ERROR: no Python interpreter found (need python3 or python)." >&2
  exit 127
fi

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BACKEND_DIR="${REPO_ROOT}/app/backend"
# Wrapper-level correlation label ONLY. Deliberately NOT named ARBICORE_AUDIT_RUN_ID
# so it can never shadow the M3 evidence-isolation selector — the REAL audit_run_id
# is generated by the canonical scanner and reported by the live phase below.
AUDIT_WRAPPER_ID="flarb_audit_wrapper:$(date -u +%Y%m%dT%H%M%SZ):$(head -c4 /dev/urandom | od -An -tx1 | tr -d ' \n')"

# ---------------------------------------------------------------------------
# Source provenance. Inside a disposable container the audited worktree is
# MOUNTED, and its `.git` is often a worktree pointer file whose real gitdir is
# NOT in the mount (git then reports "unknown"), or git refuses the mount as
# "dubious ownership". So prefer EXPLICIT provenance the operator/CI already
# knows (the exact checked-out SHA), then best-effort git, then "unknown".
# `safe.directory` is added best-effort for the mounted-worktree case.
# ---------------------------------------------------------------------------
git config --global --add safe.directory "${REPO_ROOT}" >/dev/null 2>&1 || true
GIT_SHA="${ARBICORE_VALIDATION_GIT_SHA:-$(git -C "${REPO_ROOT}" rev-parse HEAD 2>/dev/null || echo unknown)}"
GIT_BRANCH="${ARBICORE_VALIDATION_GIT_BRANCH:-$(git -C "${REPO_ROOT}" rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)}"

echo "=============================================================="
echo "ArbiCore X flash-loan readiness audit"
echo "wrapper_id   : ${AUDIT_WRAPPER_ID}"
echo "repo_root    : ${REPO_ROOT}"
echo "git_sha      : ${GIT_SHA}"
echo "git_branch   : ${GIT_BRANCH}"
echo "=============================================================="

# ---------------------------------------------------------------------------
# Mongo endpoint propagation. Several deterministic modules exercise a REAL
# Mongo (EvidenceBundlesRepo / DiscoveryQueue) and read MONGO_URL / DB_NAME from
# the environment, falling back to localhost:27017 ONLY when unset. Export them
# explicitly so every pytest-xdist worker subprocess inherits the dedicated
# VALIDATOR Mongo endpoint (never production). Print host:port only (no creds).
# ---------------------------------------------------------------------------
if [ -n "${MONGO_URL:-}" ]; then
  export MONGO_URL
  if [ -n "${DB_NAME:-}" ]; then export DB_NAME; fi
  MONGO_HOSTPORT="$("${PY}" -c 'import os,urllib.parse as u; p=u.urlparse(os.environ.get("MONGO_URL","")); print((p.hostname or "unknown")+":"+str(p.port or 27017))' 2>/dev/null || echo "unknown:?")"
  echo "mongo_target : ${MONGO_HOSTPORT} (db=${DB_NAME:-<unset>})"
  if [ -z "${DB_NAME:-}" ]; then
    echo "WARNING: DB_NAME is unset — set it for the validator (composition/services.db needs it)." >&2
  fi
else
  echo "mongo_target : <MONGO_URL UNSET>"
  echo "WARNING: MONGO_URL is not set. The Mongo-backed regression modules will fall back" >&2
  echo "         to localhost:27017 and FAIL (Connection refused) with no local Mongo." >&2
  echo "         Provide the dedicated VALIDATOR Mongo endpoint (never production), e.g. via" >&2
  echo "         deployment/compose/docker-compose.validation.yml." >&2
fi

# Deterministic guards for the safety-critical flash-loan pipeline. These are
# the invariants that MUST hold before any VPS live validation is attempted.
TESTS=(
  "tests/test_flashloan_partial_quote_economics.py"
  "tests/test_flashloan_diagnostic_provenance.py"
  "tests/test_flashloan_audit_evidence_filter.py"
  "tests/test_flashloan_canonical_audit_runner.py"
  "tests/test_z9_base_v3_liquidity_eligibility.py"
  "tests/test_gas_model_seam_failclosed.py"
  "tests/test_multichain_readiness_gate.py"
  "tests/test_flashloan_limited_live_readiness.py"
  "tests/test_m2_1_live_quote_provider.py"
  "tests/test_multichain_univ3_support.py"
  "tests/test_opportunity_engine.py"
  "tests/test_m2_2_real_tvl_gate8.py"
  "tests/test_m2_3_evidence_bundle.py"
  "tests/test_d6_1_economics_and_gates.py"
  "tests/test_economics_swap_fee_double_count.py"
  "tests/test_base_all_in_cost.py"
  "tests/test_m3_0_pre_broadcast.py"
  "tests/test_m3_0_diagnostic_ordering.py"
)

# ---------------------------------------------------------------------------
# TEST-TOOLING PREFLIGHT (FAIL-CLOSED). The disposable validation image must
# expose pytest + pytest-xdist + pytest-asyncio to the selected interpreter
# (pytest.ini declares `required_plugins = pytest-xdist`, runs `-n 2`, and sets
# `asyncio_mode = auto`). We NEVER fake a PASS when the tooling is missing:
#   present -> run the suite and report the REAL result;
#   absent  -> report TEST TOOLING UNAVAILABLE and fail closed (exit 3),
#              unless the operator opts into an isolated, pinned bootstrap.
# The preferred provisioning path is the build-time validation image
# (deployment/docker/backend/Dockerfile.validation + requirements.test.txt),
# which never touches the VPS host or any production container.
# ---------------------------------------------------------------------------
TEST_REQ="${REPO_ROOT}/deployment/docker/backend/requirements.test.txt"
if ! "${PY}" -c "import pytest, xdist, pytest_asyncio" >/dev/null 2>&1; then
  if [ "${ARBICORE_VALIDATOR_BOOTSTRAP:-0}" = "1" ]; then
    echo "Test tooling absent; ARBICORE_VALIDATOR_BOOTSTRAP=1 -> provisioning an"
    echo "ISOLATED venv from ${TEST_REQ}"
    echo "(pinned; no host / no global / no production-container mutation)."
    if [ ! -f "${TEST_REQ}" ]; then
      echo "ERROR: ${TEST_REQ} not found — cannot bootstrap test tooling." >&2
      echo "AUDIT RESULT: FAIL (test tooling unavailable — regression suite NOT executed)"
      exit 3
    fi
    VENV_DIR="$(mktemp -d)/arbicore_validator_venv"
    if ! "${PY}" -m venv --system-site-packages "${VENV_DIR}" >/dev/null 2>&1; then
      echo "ERROR: could not create an isolated venv with '${PY}'." >&2
      echo "AUDIT RESULT: FAIL (test tooling unavailable — regression suite NOT executed)"
      exit 3
    fi
    if ! "${VENV_DIR}/bin/python" -m pip install --no-cache-dir \
         --disable-pip-version-check -r "${TEST_REQ}" >/tmp/arbicore_test_bootstrap.log 2>&1; then
      echo "ERROR: pip install of test requirements failed. Tail of log:" >&2
      tail -n 25 /tmp/arbicore_test_bootstrap.log >&2 || true
      echo "AUDIT RESULT: FAIL (test tooling unavailable — regression suite NOT executed)"
      exit 3
    fi
    PY="${VENV_DIR}/bin/python"
    if ! "${PY}" -c "import pytest, xdist, pytest_asyncio" >/dev/null 2>&1; then
      echo "ERROR: test tooling still unavailable after bootstrap (fail closed)." >&2
      echo "AUDIT RESULT: FAIL (test tooling unavailable — regression suite NOT executed)"
      exit 3
    fi
    echo "Isolated test venv ready: ${PY}"
  else
    echo "==============================================================" >&2
    echo "ERROR: TEST TOOLING UNAVAILABLE" >&2
    echo "  Interpreter '${PY}' cannot import: pytest / pytest-xdist / pytest-asyncio." >&2
    echo "  This disposable validation image is NOT test-capable, so the" >&2
    echo "  deterministic regression suite CANNOT be executed. Failing closed" >&2
    echo "  (this is NOT a PASS and NOT a code-level test failure)." >&2
    echo "" >&2
    echo "  Remediation (neither option touches the VPS host or prod containers):" >&2
    echo "   1) PREFERRED — build the disposable VALIDATION image (build-time, pinned):" >&2
    echo "        docker build -f deployment/docker/backend/Dockerfile.validation \\" >&2
    echo "                     -t arbicore-x-validator:\$(git rev-parse --short HEAD) ." >&2
    echo "      then run this script inside it with the detached worktree mounted." >&2
    echo "   2) Or opt into an isolated, pinned bootstrap venv for THIS run only:" >&2
    echo "        ARBICORE_VALIDATOR_BOOTSTRAP=1 bash scripts/run_vps_validator_audit.sh" >&2
    echo "==============================================================" >&2
    echo "AUDIT RESULT: FAIL (test tooling unavailable — regression suite NOT executed)"
    exit 3
  fi
fi

cd "${BACKEND_DIR}"
echo "Running ${#TESTS[@]} deterministic regression modules..."
echo "interpreter  : ${PY} ($(command -v "${PY}"))"
# Keep the pytest failure non-fatal under `set -e` so the FAIL banner below is
# reachable; fail-closed is still enforced via the non-zero exit at the end.
STATUS=0
"${PY}" -m pytest "${TESTS[@]}" -q -p no:cacheprovider || STATUS=$?

# ---------------------------------------------------------------------------
# OPTIONAL LIVE PHASE (VPS only): run exactly ONE canonical scanner tick,
# capture the ACTUAL audit_run_id + scanner_tick_id, isolate that run's
# evidence, print the candidate ledger, and expose exact M3 selectors.
# Enabled only when MONGO_URL + DB_NAME are configured AND the operator opts in
# with ARBICORE_RUN_LIVE_AUDIT=1. READ-ONLY: never signs / broadcasts / prints
# secrets. Does not affect the pass/fail status of the deterministic guards.
# ---------------------------------------------------------------------------
if [ "${STATUS}" -eq 0 ] \
   && [ "${ARBICORE_RUN_LIVE_AUDIT:-0}" = "1" ] \
   && [ -n "${MONGO_URL:-}" ] && [ -n "${DB_NAME:-}" ]; then
  echo "--------------------------------------------------------------"
  echo "LIVE PHASE: single canonical audit tick (read-only)"
  # The Python runner emits ONLY ids/status/counts (no secrets).
  "${PY}" -m scripts.vps_canonical_audit || echo "live audit phase reported an error (fail closed)"
  echo "--------------------------------------------------------------"
fi

echo "=============================================================="
if [ "${STATUS}" -eq 0 ]; then
  echo "AUDIT RESULT: PASS (code-level flash-loan guards green)"
  echo "NOTE: code-ready only. Real VPS live validation (RPC/Mongo) is separate."
else
  echo "AUDIT RESULT: FAIL (see failures above) — NOT ready for VPS validation"
fi
echo "wrapper_id   : ${AUDIT_WRAPPER_ID}"
echo "=============================================================="
exit "${STATUS}"
