#!/usr/bin/env bash
# common.sh — shared helpers for the ArbiCore X realignment deployment.
# Sourced by every step. Provides logging, fail-fast, and auto-detection.
set -euo pipefail

# ---- paths ----
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEPLOY_ENV="${ROOT_DIR}/deploy.env"          # auto-generated by step 00
BACKEND_ENV="${ROOT_DIR}/backend/.env"       # auto-generated by step 00 (from live container)
BACKUP_DIR="${BACKUP_DIR:-}"
LOG_DIR="${LOG_DIR:-}"
# Runtime state (backups/logs) must be writable by the intended deploy user
# (e.g. `raghu`), NOT root-only /opt. Default under the repo; override via
# ARBICORE_STATE_DIR or explicit BACKUP_DIR/LOG_DIR (e.g. a pre-provisioned
# /opt/arbicore-x with correct ownership).
ARBICORE_STATE_DIR="${ARBICORE_STATE_DIR:-${ROOT_DIR}/.state}"
[ -n "$BACKUP_DIR" ] || BACKUP_DIR="${ARBICORE_STATE_DIR}/backups"
[ -n "$LOG_DIR" ]    || LOG_DIR="${ARBICORE_STATE_DIR}/logs"
COMPOSE_FILE="${ROOT_DIR}/compose/docker-compose.prod.yml"
COMPOSE_ENV="${ROOT_DIR}/compose/.env"       # auto-generated (compose var interpolation)

# ---- logging ----
c_blue(){ printf "\033[34m%s\033[0m\n" "$*"; }
c_green(){ printf "\033[32m%s\033[0m\n" "$*"; }
c_red(){ printf "\033[31m%s\033[0m\n" "$*"; }
log(){ c_blue "[$(date +%H:%M:%S)] $*"; }
ok(){ c_green "  OK  - $*"; }
die(){ c_red "  FAIL - $*"; c_red "DEPLOYMENT STOPPED. Production unchanged."; exit 1; }

need_cmd(){ command -v "$1" >/dev/null 2>&1 || die "required command not found: $1"; }

# ---- mongo shell selection (4.4.30 ships 'mongo'; newer images ship 'mongosh') ----
mongo_shell(){
  local cnt="$1"
  if docker exec "$cnt" sh -c 'command -v mongosh' >/dev/null 2>&1; then echo "mongosh"; else echo "mongo"; fi
}
mongo_eval(){ # mongo_eval <container> <db> <js>
  local cnt="$1" db="$2" js="$3" sh; sh="$(mongo_shell "$cnt")"
  docker exec "$cnt" "$sh" --quiet "$db" --eval "$js"
}

# ---- load generated env ----
load_env(){
  [ -f "$DEPLOY_ENV" ] || die "deploy.env missing — run steps/00_detect_env.sh first"
  # shellcheck disable=SC1090
  set -a; source "$DEPLOY_ENV"; set +a
}

# ---- container / network detection helpers ----
detect_one(){ # detect_one "<grep -E pattern>" ; echoes single container name or empty
  docker ps -a --format '{{.Names}}\t{{.Image}}\t{{.Ports}}' \
    | grep -iE "$1" | awk '{print $1}' | sort -u
}

# Authoritative ArbiCore Mongo container name (override via MONGO_CONTAINER env
# or deploy.env). Used to disambiguate when several Mongo containers coexist on
# the host (e.g. other apps' Mongos). Never touches data.
ARBICORE_DEFAULT_MONGO="${ARBICORE_DEFAULT_MONGO:-arbicore-x-mongo}"

# choose_mongo_container <candidates-newline-list> <explicit-or-empty> <default>
# Pure (no docker) deterministic selection. Echoes the chosen name and returns:
#   0  chosen (explicit-match | single-candidate | default-among-candidates)
#   2  explicit set but NOT among candidates
#   3  ambiguous: multiple candidates and none match the default
choose_mongo_container(){
  local candidates="$1" explicit="$2" default="$3" c
  if [ -n "$explicit" ]; then
    while IFS= read -r c; do
      [ -n "$c" ] || continue
      [ "$c" = "$explicit" ] && { printf '%s\n' "$explicit"; return 0; }
    done <<EOF
$candidates
EOF
    return 2
  fi
  local n; n="$(printf '%s\n' "$candidates" | grep -c . || true)"
  if [ "$n" = "1" ]; then printf '%s\n' "$candidates" | tr -d '[:space:]'; return 0; fi
  if [ -n "$default" ]; then
    while IFS= read -r c; do
      [ -n "$c" ] || continue
      [ "$c" = "$default" ] && { printf '%s\n' "$default"; return 0; }
    done <<EOF
$candidates
EOF
  fi
  return 3
}

# validate_mongo_container <name> — running + not explicitly unhealthy. Read-only.
validate_mongo_container(){
  local c="$1" hs
  docker ps --format '{{.Names}}' | grep -qx "$c" || return 1
  hs="$(docker inspect -f '{{if .State.Health}}{{.State.Health.Status}}{{else}}none{{end}}' "$c" 2>/dev/null || echo none)"
  [ "$hs" = "unhealthy" ] && return 1
  return 0
}

# env_kv KEY VALUE — emit a shell-safe `KEY='value'` line for a sourced env
# file. Single-quote wrapping makes semicolons, spaces, '->' and paths inert
# when the file is `source`d; embedded single quotes are escaped ('\'').
env_kv(){
  local k="$1" v="${2-}"
  v=${v//\'/\'\\\'\'}
  printf "%s='%s'\n" "$k" "$v"
}

# mongo_url_host <mongo_url> — echo the host (no creds/port/path). Pure.
mongo_url_host(){
  local rest="${1#*://}"; rest="${rest#*@}"; local auth="${rest%%[/?]*}"
  printf '%s' "${auth%%:*}"
}

# rewrite_mongo_host <mongo_url> <new_host> — swap ONLY the host, preserving
# scheme, credentials, port, path and query. Pure (no docker). Used to reconcile
# the connection to the authoritative Mongo container the preflight selected.
rewrite_mongo_host(){
  local url="$1" newhost="$2" scheme rest creds="" authority tail="" port=""
  scheme="${url%%://*}"
  rest="${url#*://}"
  case "$rest" in *@*) creds="${rest%%@*}@"; rest="${rest#*@}";; esac
  authority="${rest%%[/?]*}"
  tail="${rest:${#authority}}"
  case "$authority" in *:*) port=":${authority##*:}";; esac
  printf '%s://%s%s%s%s' "$scheme" "$creds" "$newhost" "$port" "$tail"
}
