#!/usr/bin/env bash
# common.sh — shared helpers for the ArbiCore X realignment deployment.
# Sourced by every step. Provides logging, fail-fast, and auto-detection.
set -euo pipefail

# ---- paths ----
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEPLOY_ENV="${ROOT_DIR}/deploy.env"          # auto-generated by step 00
BACKEND_ENV="${ROOT_DIR}/backend/.env"       # auto-generated by step 00 (from live container)
BACKUP_DIR="${BACKUP_DIR:-/opt/arbicore-x/backups}"
LOG_DIR="${LOG_DIR:-/opt/arbicore-x/logs}"
COMPOSE_FILE="${ROOT_DIR}/compose/docker-compose.prod.yml"
COMPOSE_ENV="${ROOT_DIR}/compose/.env"       # auto-generated (compose var interpolation)

# ---- logging ----
c_blue(){ printf "\033[34m%s\033[0m\n" "$*"; }
c_green(){ printf "\033[32m%s\033[0m\n" "$*"; }
c_red(){ printf "\033[31m%s\033[0m\n" "$*"; }
log(){ c_blue "[$(date +%H:%M:%S)] $*"; }
ok(){ c_green "  OK  - $*"; }
die(){ c_red "  FAIL - $*"; c_red "DEPLOYMENT STOPPED. Production unchanged."; exit 1; }

need_cmd(){ command -v "$1" >/dev/null 2>&1 || die "required command not found: $1"; }

# ---- mongo shell selection (4.4.30 ships 'mongo'; newer images ship 'mongosh') ----
mongo_shell(){
  local cnt="$1"
  if docker exec "$cnt" sh -c 'command -v mongosh' >/dev/null 2>&1; then echo "mongosh"; else echo "mongo"; fi
}
mongo_eval(){ # mongo_eval <container> <db> <js>
  local cnt="$1" db="$2" js="$3" sh; sh="$(mongo_shell "$cnt")"
  docker exec "$cnt" "$sh" --quiet "$db" --eval "$js"
}

# ---- load generated env ----
load_env(){
  [ -f "$DEPLOY_ENV" ] || die "deploy.env missing — run steps/00_detect_env.sh first"
  # shellcheck disable=SC1090
  set -a; source "$DEPLOY_ENV"; set +a
}

# ---- container / network detection helpers ----
detect_one(){ # detect_one "<grep -E pattern>" ; echoes single container name or empty
  docker ps -a --format '{{.Names}}\t{{.Image}}\t{{.Ports}}' \
    | grep -iE "$1" | awk '{print $1}' | sort -u
}
